### ISSUE TITLE
Option to set size of select?

### ISSUE THREAD

**Issue by dzg** [wotamann/vuetify-form-base#1]
Is there a way to force a select field to be a certain size rather than drop-down?

**Comment by wotamann** [comment]
I don't understand exactly what you're saying. 

vuetify-form-base is using [vuetify-select](https://vuetifyjs.com/en/components/selects) and most of the Properties can be used, by defining them in your Schema-Section:

`select: { type: 'select', label: 'Selection', clearable: true, menuProps: {maxHeight:100}, color: 'teal', box: true, height: '4rem', items: ['A', 'B', 'C','D', 'E', 'F'] },`

**Comment by dzg** [comment]
First, sorry, I just realized this is a fork of the main vuetify project, yes?

But maybe you can still help me ... I am wanting a select like this: https://codepen.io/dzg/pen/LaaRYR

Where you can see the options in a list

**Comment by wotamann** [comment]
No, this is **not** a fork of vuetify, but vuetify-form-base uses the input-controls of vuetify to represent the form. 

Okay, I understand what you mean. I have checked the api of vuetify , but I think the desired appearance is unfortunately not available using v-select.

**Comment by wotamann** [comment]
I have added a **list** and **array** control!
Take a look at the [Demo  ](https://wotamann.github.io/) and select Menu '**Values with Arrays**'. Maybe this will help you, for details please look at the sourcecode of this example
