### ISSUE TITLE
Rendering form from json file

### ISSUE THREAD

**Issue by raj5152** [wotamann/vuetify-form-base#10]
How to add validation rules from .json file and dynamically change or add the custom color for fields in vuetify-form-base?

**Comment by wotamann** [comment]
Define your Schema in computed Section and then change 

> this.myColor 


```
data(){
  return {
    myColor: 'green',
    myValue: { 
      title: 'ABC'
    },
    ...
  }
},

computed: {
  mySchema(){
    return {
      title: { type: 'text', color:  this.myColor, flex: 8 }
    }
  }    
}
```

**Comment by raj5152** [comment]
Is there any way to fetch the colors dynamically from json file?

**Comment by wotamann** [comment]
It's up to you how you get your colors. If you got your fetchedColors then you must update 

`this.myColor = fetchedColors `

I hope this will help!
