### ISSUE TITLE
How to use the masks?

### ISSUE THREAD

**Issue by GiovannyLucas** [wotamann/vuetify-form-base#12]
I try to follow as stated in the documentation, however, when I put in place to mask as in vuetifyjs does not run.

Vuetify: 2.0.0
Vue: 2.6.10
Lodash: 4.17.3

**Comment by wotamann** [comment]
I don't understand your request, please can you give me an example

**Comment by GiovannyLucas** [comment]
![image](https://user-images.githubusercontent.com/41789184/65442973-8e966580-de03-11e9-8d5e-0e8c6c10c2fc.png)

**Comment by wotamann** [comment]
With Vuetify 1.5 the schema property 

> mask:'##.##' 

should work out of the box. 

Vuetify 2.0 use internal [vue the mask](https://vuejs-tips.github.io/vue-the-mask/), I have added this to vuetify-form-base and you can use it as described in section **Directive Usage**
 
 ```
myValue: {
   creditcard: '12345678',
 },
 mySchema: {
   // Info Mask https://vuejs-tips.github.io/vue-the-mask/
   creditcard: { type: 'text', mask: '####-####-####-####', flex: 4 } 
 }
```
