### ISSUE TITLE
Date picker for a v-text-field?

### ISSUE THREAD

**Issue by Sashley** [wotamann/vuetify-form-base#16]
Looks very promising for basic schema forms (thank you), but I'm struggling to find an approach to integrate a date picker into a v-text-field. Have tried using both slots and a custom typeToComponent extension without luck. Any guidance or hints would be greatly appreciated. TIA

**Comment by wotamann** [comment]
You can make a custom 'typeToComponent' and change 

> date: 'v-date-picker'

to 

> date: 'v-text-field'

then you will get the vuetify 'text-field' with type date 
````
const typeToComponent = {
/...  
  date: 'v-text-field',
/...  
  datepicker: 'v-date-picker',
/...  
}
```

**Comment by Sashley** [comment]
Thanks. Issue resolved.
