### ISSUE TITLE
Input event not fired

### ISSUE THREAD

**Issue by paragasu** [wotamann/vuetify-form-base#17]
I want to listen to the input event so i can dynamically add items on `autocomplete`.
The selection will be updated as the user type in the value on the autocomple.

However, the `onInput` method never get called.

`<v-form-base :schema="schema" :value="value" @input="onInput">`

**Comment by wotamann** [comment]
Based on vuetify the control `v-autocomplete` fires only an [blur and change](https://vuetifyjs.com/en/components/autocompletes) event. so you can't query an input event either. If you want control your input you can use `combobox`
