### ISSUE TITLE
How to add custom widget

### ISSUE THREAD

**Issue by paragasu** [wotamann/vuetify-form-base#19]
What is the best way to add custom input widget / component ?

**Comment by OdiljonQurbon** [comment]
I'm also interested in this. Thanks.

**Comment by miguelrk** [comment]
Hey! I've been enjoying vuetify-form-base a lot! It really rocks! 

After using it for a while now, I am starting to need the possibility of creating custom components/formfields. This could be similar to how [vue-form-generator](https://github.com/vue-generators/vue-form-generator) does it. 

Anyways, is this feature currently planned? I would also be very interested!

**Comment by wotamann** [comment]
Maybe this can help! 

Create component 'customcomponent.vue'

```
<!--  /component/customcomponent.vue -->
<template>
  <div >
    <h4>Custom Control Object</h4>
    <v-text-field v-model="value.a" @input="$emit('input', value)" label="A"></v-text-field>
    <v-text-field v-model="value.b" @input="$emit('input', value)" label="B"></v-text-field>
    <v-btn small color="grey" dark  @click="clear">Clear both</v-btn>    
  </div>
</template>

<script>
export default {
  props: ['type','value'],    
  methods:{
    clear(){
      this.value.a = null
      this.value.b = null
      this.$emit('input', this.value)
    }    
  }
}
</script>
```
And then register this component globally in main.js. 
IMPORTANT: You must prepend component name with 'v-'  like  'v-customname'
```
Vue.component('v-custom1', () => import('@/components/customcomponent.vue') )
```
Now you can use this Component with 
 `
model: { mycustom: { a:'AAA', b:'BBB' },
schema: {  mycustom: { type: 'custom1' } }.`

**Comment by miguelrk** [comment]
Thanks for the quick respnse! That is just what I needed, as flexible as possible! Thanks a lot! I will give it a try

**Comment by wotamann** [comment]
in version 0.2.4 any global registered component is possible. It is not longer necessary to prefix the component name with 'v-'

**Comment by wotamann** [comment]
Lookup for a 'v-'component signals, that no GLOBAL registered component was found. 

I don't know how you registered your component. Because HTML is case-insensitive maybe your uppercase name is the problem (see  [Vue-Discussion](https://github.com/vuejs/vue/issues/2308) here)

```
// Global definition in 'main.js'
// works
Vue.component('custom-basic-a', () => import('@/components/customcomponent-basic.vue') )
Vue.component('customBasicB', () => import('@/components/customcomponent-basic.vue') )
// doesn't work
Vue.component('custom-basic-c', () => import('@/components/customcomponent-basic.vue') )
```

```
// works
schema: { custom1: { type: 'custom-basic-a', label:'Component - Basic' }  }
schema: { custom1: { type: 'customBasicB', label:'Component - Basic' }  }
// doesn't work
schema: { custom1: { type: 'customBasicC', label:'Component - Basic' }  }
```

**Comment by joxper** [comment]
I am registering it as a plugin, because it comes from an external library

```
import Vue from 'vue'
import VueTelInputVuetify from 'vue-tel-input-vuetify'

Vue.use(VueTelInputVuetify)
```

and in the VueTelInputVuetify setup is registering the component as:

```
Vue.component('vue-tel-input-vuetify', VueTelInputVuetify);
```

I tried like like:
```
  profileSchema = {
    phone: {
      type: 'VuetifyPhoneInput',
      label: 'Phone',
      class: 'py-0 px-1',
      outlined: true,
    },
  };

and

  profileSchema = {
    phone: {
      type: 'vue-tel-input-vuetify',
      label: 'Phone',
      class: 'py-0 px-1',
      outlined: true,
    },
  };
```

Still have the same error, where its trying to get the v- component
![image](https://user-images.githubusercontent.com/7101877/91214484-6e59df80-e713-11ea-83be-edd24d81dc29.png)

thanks

**Comment by joxper** [comment]
Only when registered like this it works

```
Vue.component('v-vue-tel-input-vuetify', VueTelInputVuetify);
```
so custom components without the v- wont work

**Comment by wotamann** [comment]
registration is checked in `mapTypeToComponent` using registered components from `Vue.options.components`

try to log `Vue.options.components` after registration to see if there is a `vue-tel-input-vuetify` component.


```
// MAP TYPE TO COMPONENT
    mapTypeToComponent(type) {
      // merge global registered components into typeToComponent Object
      const allTypeComponents = { ...typeToComponent, ...Vue.options.components}
      // const typeToComponent -> maps type to according v-component 
      // ie. schema:{ type:'password', ... } to specific vuetify-control or default to v-text-field'

      return allTypeComponents[type] 
          ? allTypeComponents[type] 
          : `v-${type}` // add v- to schema type
    },
```

**Comment by wotamann** [comment]
this setup worked for me

main.js
```
import Vue from 'vue'
import App from '@/App.vue'
import VueTelInputVuetify from 'vue-tel-input-vuetify'
import vuetify from '@/plugins/vuetify'

Vue.use(VueTelInputVuetify, {
  vuetify,
});

console.log('VueTelInputVuetify', VueTelInputVuetify);

console.log('Components', Vue.options.components)

new Vue({
  el: '#main',
  vuetify,
  render: h => h(App)
})
```
use component  in vue file
```

schema: {  myTel: { type:'vue-tel-input-vuetify' }
```

**Comment by joxper** [comment]
Hi @wotamann thanks for taking your time,
I log the components, seems like the component is present but still is looking for the v- type, but is OK I will use it with the v- and will solve the problem.
![image](https://user-images.githubusercontent.com/7101877/91284463-393da380-e78c-11ea-8a50-d2833013c711.png)

thanks for the awesome library
