### ISSUE TITLE
Populating the data from Serve

### ISSUE THREAD

**Issue by sakthiaseer** [wotamann/vuetify-form-base#22]
hi Team,

I want to populate the data from Server in to form base. I couldn't generate the JSON like your format. I able to hard code manually but from array i am not able generate as generic.

Thanks,
Sakthi

**Comment by wotamann** [comment]
vuetify-form-base can handle standard JSON Format. If you work with other datatypes you have to bring it into a valid JSON-Format. 
If you want to load async Data from Server you can look at "Lazy Loading Component for Async-Data" in Example
