### ISSUE TITLE
Nested Data-Object

### ISSUE THREAD

**Issue by bajki** [wotamann/vuetify-form-base#25]
Hi,
i need help about how to add subheader to nested object.

So if i create object data like this:
mySchema: {
    section_title: { type: 'text', label: 'Section title'},
    section_subtitle: { type: 'text', label: 'Section subtitle'},
    feature_1:{
         title: { type: 'text', label: 'Title'},
         subtitle: { type: 'text', label: 'Subtitle'},
       } ,
    feature_2:{
         title: { type: 'text', label: 'Title'},
         subtitle: { type: 'text', label: 'Subtitle'},
       }  
     feature_3:{
         title: { type: 'text', label: 'Title'},
         subtitle: { type: 'text', label: 'Subtitle'},
       }  
    }
How to separate it in groups so it goes:

Section title input
Section subtitle input
_______
Subheader: Feature 1
Title input
Subtitle input
_______
Subheader: Feature 2
Title input
Subtitle input
_______
Subheader: Feature 3
Title input
Subtitle input

Because now inputs are one after another.

**Comment by wotamann** [comment]
If you have an array of features you can try the following:

```
mySchema: {

section_title: { type: 'text', label: 'Section title'},

section_subtitle: { type: 'text', label: 'Section subtitle'},

features: { 
   type: 'array', 
   schema: { 
      title: { type: 'text', label: 'Title'}, 
      subtitle: { type: 'text', label: 'Subtitle'} 
   }
} 
```

**Comment by wotamann** [comment]
Look at [Example ](https://wotamann.github.io/) to Section 'Edit Data-Array'
