### ISSUE TITLE
Tooltips with slots?

### ISSUE THREAD

**Issue by Rambone** [wotamann/vuetify-form-base#26]
Hello, is there a possibility to integrate tooltips via slots? I have not been able to do it yet and would be very grateful for a hint. My current solution includes a modification of VFormBase.vue, which I'm not really happy about. It would be great to control the tooltips via the schema. TIA

**Comment by wotamann** [comment]
Tooltip added, see in example Section 'Simple' or 'CSS'

Use Text:
> schema: {  name: { type: 'text', tooltip: 'My Tooltip Text' }, ...  }

or use Slot:

> schema: {  name: { type: 'text', tooltip: true }, ...  }
```
HTML
 <!-- TOOLTIP SLOT -->
 <div slot="slot-tooltip" slot-scope="slotProps">
    {{ slotProps.obj.schema.tooltip }} has value '{{ slotProps.obj.value }}'
 </div>
 <!-- TOOLTIP SLOT - new Syntax VUE 2.6.0 -->
 <template v-slot:slot-tooltip="slotProps">
      {{ slotProps.obj.schema.tooltip }} with Value: {{ slotProps.obj.value }}
 </template> 

STYLE
  .v-tooltip__content { background-color: #F66; }
```

**Comment by wotamann** [comment]
also possible to control color and position of tooltip

> schema: { name: { type: 'text',  tooltip: { color: 'green', label: 'File Selection', left: true }, ... }

**Comment by Rambone** [comment]
Hi, thank you for your efforts. This is going in exactly the direction I had in mind. Is it possible to have the tooltip activator not on the v-flex element but rather on the prepenIcon/apendIcon or button? That would certainly be easier for the user to understand.
TIA

**Comment by Rambone** [comment]
Addendum: the best position for the icon with activator would be at the example of the v-textfield the append-outer-slot or at the v-checkbox/radio/switch the append-slot.

**Comment by wotamann** [comment]
Tooltip on button works! 

`
   btn1: { type: 'btn',  tooltip: 'Button' }
`

I have been looking for but apparently vuetify 2.0 doesn't support binding v-tooltip to prepend-inner-icon 
```
//   does not work !!!!
<v-tooltip left slot="prepend-inner">
        <template v-slot:activator="{ on }" >        
               <v-text-field v-on="on" prepend-inner-icon="add" >                      
               </v-text-field>
        </template>      
        <span>Left tooltip</span>     
</v-tooltip>
```
Maybe someone has an idea or someone can help !

**Comment by Rambone** [comment]
Hello, it works if the tooltip does not act as a wrapper of the field. Had solved it with an SFC at first, but I thought it completely twisted the logic of your work. 

`<v-text-field>
    <v-tooltip slot="append-outer">
        <template v-slot:activator="{on}">
            <v-icon @... v-on="on">
            Tooltip icon
            </v-icon>
        </template>
            <span>Tooltip content</span>
    </v-tooltip>
</v-text-field>`

**Comment by wotamann** [comment]
THX for your comment and yes, you're absolutely right: This change would twist structure and logic of vuetify-formabse
