### ISSUE TITLE
model not updating form

### ISSUE THREAD

**Issue by whaleforever** [wotamann/vuetify-form-base#34]
for example using 

```
<v-form-base :model="test" :schema="test"/>
...
<script>
...
<!-- at some point in the code -->
this.test = {item:"something"}
...
</script>
```

While the "test" variable has the value, but it won't show up in generated form. It shows an empty form. I got this bug after I updated vue and vuetify to the newest version. Looking at the code it seems setValue not updating correctly. Is there a solution for this?

**Comment by wotamann** [comment]
Vuetify-form-base is tested and working with the Vue 2.6.11  and Vuteify 2.2.27

Please give me a detailed explanatory example of the error you noticed !

#### Issue description
example on codesandbox.io reproducing this issue

#### Steps to reproduce the issue

#### Environment description
Vue ?
Vuetify ?

**Comment by whaleforever** [comment]
hi, 
Thank you for fast response.
I have created a project to show the error  (i'm not quite familiar with codesandbox.io)
https://github.com/whaleforever/evdt.

if you press the pen key it won't show anything.

without v-form-base it works fine: 
![Screenshot from 2020-05-11 01-45-19](https://user-images.githubusercontent.com/5946704/81507669-214f2a80-9329-11ea-9a62-a819c15c2965.png)

with v-form-base the data not showing:
![Screenshot from 2020-05-11 01-40-02](https://user-images.githubusercontent.com/5946704/81507671-2318ee00-9329-11ea-9636-1ae4e7f4285f.png)

thanks.

**Comment by wotamann** [comment]
Hi, you are allright!

I think 'model' /'value' had no dynamic binding after adding the 'model' prop 
I will do this in next update

But you should find a simplified sample of yours with a working vuetify-form-base.vue file in dir components
https://github.com/wotamann/evdt

**Comment by wotamann** [comment]
> Update with dynamic binding of <v-form-base> attributes:

before the last update, the object of the attributes 'model', 'schema' and 'col' passed during initialization could be edited but not exchanged. Now these attributes 'model', 'schema' and 'col' can also be changed during runtime.
