### ISSUE TITLE
There is no opportunity to add vuetify v-text-field attr

### ISSUE THREAD

**Issue by issasami** [wotamann/vuetify-form-base#36]
How can i add for example - `solo` or `outlined` or `filled` etc just like in vuetify ?

It will be great to configure text-field with this functionality.

Thanks for your time and work, its really awesome.

**Comment by wotamann** [comment]
Use Vuetify Controls API: 

Set Attribute in Schema to 'true'
Props in Vuetify-Controls in kebab-case must be converted to camelCase in Schema-Definition. 

```
mySchema: { 
    name: { type:'text', appendIcon:'menu', backgroundColor:'red', outlined:true }  
  }
```

**Comment by issasami** [comment]
@wotamann Thanks got it, sorry i wasn't found it in readme.
