### ISSUE TITLE
Cascading selection

### ISSUE THREAD

**Issue by bajki** [wotamann/vuetify-form-base#37]
How to make this dynamic so i dont need log function to push items to another array?

Thanks

**Comment by wotamann** [comment]
Only the selectable items of your selections are synchronized, programmatically changing the schema can't update your value. You need 'input' event to update the value in the dependent selection field according to your requirements. 

Look at  [cascading Example](https://github.com/wotamann/vuetify-form-base/blob/master/example/src/components/selectioncascading.vue)

```
 data () {
    return {
      myValue: {
        selection1: ['A', 'B'],
        selection2: 'B',
      },
      
    }
  },
  computed: {
    mySchema() {
      return {
        selection1: { type: 'select', items:['A', 'B','C'], multiple: true },
        selection2: { type: 'select', items: this.myValue.selection1 },
      }
    }
  },
```
