### ISSUE TITLE
Populate model with an object

### ISSUE THREAD

**Issue by Teehn** [wotamann/vuetify-form-base#39]
Is it possible to populate model field with an object value?
Im trying to do it like in example below - but it cannot be handled in flattenObjects method .

thanks! 

model:
```
{
   "somefield": "{id:1,value:'Some value'}",

}
```

schema:
` "somefield": {
      "type": "select",
      "returnObject": true
       itemText: "value",
       itemValue: "id",
   },`

**Comment by wotamann** [comment]
I have reworked the flattenObjects method handling the special schema-key 'type' and it should now be possible to pass an object to the model. Your requested example should work 

```
myModel: { selectObject: {name:'This is A', val:'A'} },

mySchema: { selectObject: { type: 'select', returnObject:true, itemText:'name', items:...  }
```

**Comment by Teehn** [comment]
Thank you! It work really great!

**Comment by andrelec1** [comment]
add this to the readme ;)
