### ISSUE TITLE
fromCtrl and toCtrl not changing the model

### ISSUE THREAD

**Issue by jorgv** [wotamann/vuetify-form-base#43]
Hello,

I am trying to sync two fields, so the second field can use the value of the first one:

```  schema = {

    email: {
      type: 'text',
      label: 'Email',
      rules: [rules.email],
    },
    username: {
      type: 'text',
      label: 'Username',
      readonly: true,
      toCtrl: ({ data }) => data && data.email,
      fromCtrl: ({ data }) => data && data.email,
    },
}
```
on the ui, the value is change whenever email field is modified, but when the form is submitted the username model value is empty.

Is there other way I can synchronize the fields or this is a bug?

using: 
    "vuetify": "2.3.4",
    "vuetify-form-base": "^0.1.22",

thanks

**Comment by wotamann** [comment]
Try this
```
username: {
          type: 'text',
          label: 'Username',
          readonly:true,
          toCtrl: ({  data }) => { data.username = data.email; return data.username},          
        }
```

**Comment by jorgv** [comment]
thank it works as expected!

thanks for this great plugin
