### ISSUE TITLE
CDN Version

### ISSUE THREAD

**Issue by Mashiane** [wotamann/vuetify-form-base#46]
Good day, I am using vuetify via the cdn version and thus not using imports.

Is it possible for you to also provide a compiled version of your component to JavaScript please. If there is a way I can use it as is on the <script> tag that will also be fine you can advise.

Thank you again for this wonderful amazing piece of art.

**Comment by wotamann** [comment]
Nice to hear your opinion. You can find now a compiled umd-file at 

[https://unpkg.com/vuetify-form-base@0.2.4/umd/vFormBase.umd.min.js](https://unpkg.com/vuetify-form-base@0.2.4/umd/vFormBase.umd.min.js)

and a working html file at 

`vuetify-form-base/example/public/index-cdn.html`

**Comment by Mashiane** [comment]
Thank you very much appreciated.

**Comment by Mashiane** [comment]
Hi, if you dont mind me asking, has this been updated to the latest version of vuetify-form-base?

Thanks
