### ISSUE TITLE
Vuetify has no v-array component for data-arrays

### ISSUE THREAD

**Issue by alexisread** [wotamann/vuetify-form-base#5]
Could you please clarify the documentation on data-arrays? Trying to use them, I get that the custom component v-array is not defined.
Are we supposed to create a custom component ourselves, and if so, could you provide a sample component?
Otherwise, which Vuetify component should we be using, list ie. change 'array' to 'list'? The array data might require manipulating to fit the component in this case.

Thanks

**Comment by wotamann** [comment]
Thank you for your interest!
Possibly the NPM Packages have not been up to date. I just made an update. If you have further problems please send me an example with non working code

**Comment by alexisread** [comment]
Thanks, I'm not sure if the npm push worked, but I was using a contracted form of v-form-base v-form-base :value="myValue" :schema="mySchema" @update="update" /> which definitely doesn't work. Using the updated npm and the full form worked fine for me.
