### ISSUE TITLE
I request a piece of advice...

### ISSUE THREAD

**Issue by Mashiane** [wotamann/vuetify-form-base#51]
Hi there

For a while I have been working on a designer app using Vuetify and now want to adopt some part of it to vuetify-form-base. Below is the schema of what my app gets to build, this I later to create an UI at runtime as a mock. Im using this basically for code generation.

I want now to somehow provide a preview-screen of what the for will look like using a dialog.

Name - the database table field name
Title - should appear on the label of each component
Component - the type of component to render
R - row 
C - column
OS - OX - offsets
SS - SX - size per device

![designer](https://user-images.githubusercontent.com/5799306/89731082-99221380-da44-11ea-90a2-bd41790d3c79.jpg)

Most of the details here are linked to an underlying database table. For example, for each field, I provide it a title, the row location and column location. This also goes for the component type. As one can use different devices, I also indicate the sizes for the devices. What Id like to know is what is the best approach to bring a schema like this to vuetify-form-base? Do I create schemas per each row for vuetify-form-base? considering that some rows might have different sizes per device?

This is my output from my designer without using vuetify-form-base at the moment generated from the definitions above.

![designer1](https://user-images.githubusercontent.com/5799306/89731396-046ce500-da47-11ea-9f81-abad5581efeb.jpg)

Thank you.

**Comment by wotamann** [comment]
I think you have to create one key in schema for each row and control the layout with [Vuetifys GRID](https://vuetifyjs.com/en/components/grids/) system. But if you want a dynamic schema you must use a **computed schema**. See Code in 'Responsive Grid' Example 
```
schema: {
  feverchills: {
      type: 'checkbox',
      label:'fever/chills'
      col: {
         cols: 6,  // Column
         sm: 12
      },
      order: {
         order: 'last'
      },
      offset: {
         offset-sm: 1  // OS OX
      }
   },
}
```

**Comment by Mashiane** [comment]
Thank you

**Comment by Mashiane** [comment]
Thank you
