### ISSUE TITLE
Month picker display issue

### ISSUE THREAD

**Issue by nuluferdmello** [wotamann/vuetify-form-base#52]
Hi, in my project I am trying to use the month picker in menu, but i didn't find the correct options in vuetify-form-base schema's. Please suggest a solution to fix my issue.

**Comment by wotamann** [comment]
You can try 

`schema:{ date: { type: 'date', ext:'month' } }`

**Comment by nuluferdmello** [comment]
Hi, thanks for your reply.

I did try that but it shows a normal month calendar and i am looking for something like what they have in vuetify like this.
https://vuetifyjs.com/en/components/date-pickers/#month-pickers-in-dialog-and-menu

**Comment by wotamann** [comment]
I made an update in V 0.2.5 and this should work - see example 

> Date, Time, Color as native HTML-Type, Menu and Pickers


Problem: any 'type' prop in vuetify-control or your custom component is shadowed from v-form-base schema 'type' property
  if `<v-datepicker type="month">` control needs type="month" then you can solve this with 'typeInt' -> 

`schema { monthselect: { type:'date', typeInt:'month'}`
`schema { monthselect: { type:'date', typeInt:'month', ext:'text' }`

components internal 'type' mapping works in this order `typeInt || ext || type` 
`schema { vc: { type:'v-control', typeInt:'any-v-type', ext:'any-ext' }` -> `<v-control type ="typeInt || ext || type" >`

```
"monthpicker": {
      "type": "date",
      "ext": "text",
      "typeInt": "month",
      "color": "green",
      "locale": "de",
      "prependIcon": "event",
      "label": "Month"
   },
```

**Comment by nuluferdmello** [comment]
Thank you for the update. It worked.

**Comment by nuluferdmello** [comment]
Hi,

Following on the issue above, its working perfectly with the solution that you provided. 

**But is there a way to close the picker menu once the month is selected? currently i need to click outside the picker menu to close it.**
