### ISSUE TITLE
Error using v-form-base in dialog

### ISSUE THREAD

**Issue by brunosmm** [wotamann/vuetify-form-base#56]
Hello,

First, thanks for sharing this lib, seems really impressive! 👍 

I am trying to use it, creating a component with a dialog and the v-form-base inside, code below, but I am getting an error on the console. The form is using the schema and model from the readme file. I am using the version 0.2.6.

ERROR:
![image](https://user-images.githubusercontent.com/1554850/92330320-dab6d600-f065-11ea-9598-b40e9091a49e.png)

CODE:
```vue
<template>
    <v-dialog v-model="dialog" max-width="500px">
        <v-card>
            <v-form>
                <v-form-base
                    cols="12"
                    :model="myModel"
                    :schema="mySchema"
                    @input="handleInput"
                />
            </v-form>
        </v-card>
    </v-dialog>
</template>

<script>
import VFormBase from 'vuetify-form-base';
export default {
    name: 'NewProductDialog',
    components: { VFormBase },
    props: {
        dialog: { type: Boolean, default: false },
    },
    data() {
        return {
            myModel: {
                name: 'Jumo',
                password: '123456',
                email: 'base@mail.com',
                checkbox: true,
                select: 'Jobs',
            },
            mySchema: {
                name: { type: 'text', label: 'Name' },
                password: { type: 'password', label: 'Password' },
                email: { type: 'email', label: 'Email' },
                checkbox: { type: 'checkbox', label: 'Checkbox' },
                select: {
                    type: 'select',
                    label: 'Select',
                    items: ['Tesla', 'Jobs', 'Taleb'],
                },
            },
        };
    },
    methods: {
        handleInput(val) {
            console.log(val);
        },
    },
};
</script>

<style scoped></style>
```

Can anyone help with this problem?

Cheers

**Comment by brunosmm** [comment]
After reading other issues, I figure out the solution.
It will be really great to update the Readme file with steps to run the example.

The steps I made was:

1. `npm instal vuetify-form-base`
2. Create the component with the code from my first comment.
3. Change the file src/plugins/vuetify.js and change to import the necessary components and directive:
```js
import Vue from 'vue';
import Vuetify, {
    VRow,
    VCol,
    VTextField,
    VTooltip,
    VCheckbox,
    VSelect,
} from 'vuetify/lib';
import { Ripple, Intersect, Touch, Resize } from 'vuetify/lib/directives';

Vue.use(Vuetify, {
    components: { VRow, VTooltip, VCol, VTextField, VCheckbox, VSelect },
    directives: { Ripple, Intersect, Touch, Resize },
});

export default new Vuetify({});
```

I am happy to change the readme file update and send a pull request, let me know if you want this contribution @wotamann .

Cheers

**Comment by wotamann** [comment]
There is a hint under **Installation**

> For proper working you need a Vue.js Project with Vuetify 2.0 installed. Get started with Vuetify, the world’s most popular Vue.js framework for building feature rich, blazing fast application here.
> 
>     INFORMATION: Vue-Loader doesn't autoload components, because Vuetify-Form-Base use built in Vue
> 
> <component is="my-component" />
> 
> and therefore Components must be manually imported. 

But I would be pleased if you would clarify and improve this point. Please send an PR for an update of the readme file

**Comment by brunosmm** [comment]
Hi @wotamann ,

Here the pull request updating the readme: https://github.com/wotamann/vuetify-form-base/pull/57 

Cheers,
Bruno
