### ISSUE TITLE
Month picker does not auto close on selection

### ISSUE THREAD

**Issue by nuluferdmello** [wotamann/vuetify-form-base#58]
Hi,

Is there a way to close the picker menu once the month is selected? currently i need to click outside the picker menu to close it.

_Originally posted by @nuluferdmello in https://github.com/wotamann/vuetify-form-base/issues/52#issuecomment-690317620_

**Comment by wotamann** [comment]
Hi, 

in 0.2.7 you can control text-datepicker with schema prop 'menu'

```
schema: { 
    month: { 
        type: 'date', 
        ext: 'text',
        typeInt: 'month', 
        menu: { closeOnContentClick:true, nudgeRight:200 }, 
        locale: 'en', 
        label: 'Month' 
    },
...
```
See it working at [Date/Time Picker Example](https://wotamann.github.io/)

**Comment by nuluferdmello** [comment]
Hi,

Thank you for the new update. It worked beautifully 👍
