### ISSUE TITLE
Using Vuetify native classes

### ISSUE THREAD

**Issue by mcormackalan** [wotamann/vuetify-form-base#6]
Hi !

The project is awesome so first of all, congratulations.
I'm checking the docs but I couldn't find any related to use Vuetify element classes like "Solo", "Box" and the rest.

There's any way to use them? 

Thank you !

**Comment by wotamann** [comment]
Thank you for your interest!

The property of supported vuetify components like 'textfield' can be specified as property with the value 'true' in Schema Definition. 

```
mySchema: {
  name: { type: 'text', box: true, ... },
}
```

But beware, not all properties of the individual components are supported.
