### ISSUE TITLE
Tooltip Bug

### ISSUE THREAD

**Issue by Mashiane** [wotamann/vuetify-form-base#60]
Hi

To reproduce, add a text with a tooltip.
Add a date picker

Result: Number tooltip shown on date

Expected Result: Number tooltip to show closer to the parent control.

![TooltipError](https://user-images.githubusercontent.com/5799306/94863780-47da4300-043b-11eb-86d2-7ce94fbef068.jpg)

**Comment by wotamann** [comment]
There is no Bug! You can use 'tooltip' with an an object and set the position (see vuetify documentation). 

```
mySchema: {
        name: { type: 'text', tooltip: { label: 'Name', left: true, color:' green' } },
...
```

or work with 

> Tooltip - Slot

 see example 'CSS, Slots, Tooltips & Buttons'

**Comment by Mashiane** [comment]
Thank you.
