### ISSUE TITLE
How to set up Radio to use key value pairs

### ISSUE THREAD

**Issue by Mashiane** [wotamann/vuetify-form-base#61]
Hi there

In the examples for the radio, its using an array. How can one use an array of objects like the select with itemValue & itemText for selects etc.

Thanks

**Comment by wotamann** [comment]
Please, could you give an example to clarify your question

**Comment by Mashiane** [comment]
![KeyValueRadio](https://user-images.githubusercontent.com/5799306/94996986-6447be00-05a8-11eb-83bb-785f73fd229b.jpg)

This is an example from another js lib.

**Comment by Mashiane** [comment]
Perhaps this can shed more light as the explanations might be missing the crux:

`<v-radio
        v-for="item in items"
        :key="item.id"
        :label="{{ item.name }}"
        :value="item.name"
      ></v-radio>`

**Comment by wotamann** [comment]
Vuetify styles 'radio' with prop [label & value](https://vuetifyjs.com/en/components/radio-buttons/) 

This should work
```
schema: { 
  myRadioGroup: { 
    type: 'radio', options: [ {label:'Label A', value:'A'}, {label:'Label B', value:'B'} ] 
  }
}
```

**Comment by Mashiane** [comment]
Perfect thanks.
