### ISSUE TITLE
How does one bind the "items" to an attribute

### ISSUE THREAD

**Issue by Mashiane** [wotamann/vuetify-form-base#62]
Hi there

Instead of specifiying items for selects etc like items = ['A', 'B', 'C']

How do I achieve the same by assigning such to the state like :items="itemSource", where itemSource is stored on the Vue instance?

Thank you.

**Comment by wotamann** [comment]
use computed schema
```
data () {
    return {
      items: ['A', 'B'],
      myModel: {
        selection: 'A',
      },
      
    }
  },
  computed: {
    mySchema() {
      return {
        selection: { type: 'select', items:this.items },
      }
    }
  },
```

**Comment by Mashiane** [comment]
Thank you.
