### ISSUE TITLE
How to detect click:minute event & then close timepicker dialog

### ISSUE THREAD

**Issue by Mashiane** [wotamann/vuetify-form-base#66]
Hi there

For the time picker control. I'd like to only close the time picker when the minutes are clicked. I have set closeOnContentClick to false as I dont want that behavior. How can I achieve that?

![MiniteClick](https://user-images.githubusercontent.com/5799306/95003749-a7268780-05e2-11eb-97b7-34af84a19af6.jpg)
 

The v-time-picker component has a click:minute event.

Thanks

**Comment by wotamann** [comment]
Based on your proposal i will integrate click:hour, click:minute, click:second in the next version

**Comment by wotamann** [comment]
added click:second , minute, hour event in [Time-Picker](https://wotamann.github.io/pickers)
