### ISSUE TITLE
Combo box / selects don't open when you click the arrow in the field

### ISSUE THREAD

**Issue by DevBrent** [wotamann/vuetify-form-base#68]
It seems like VFormBase is emitting an update which might be messing up the combo boxes when you click the icon within the combo box dropdowns.

Has anyone else run into this?

Edit: You can reproduce on https://wotamann.github.io/

**Comment by RyanCwynar** [comment]
I created a PR to address this
https://github.com/wotamann/vuetify-form-base/pull/69

**Comment by wotamann** [comment]
Thanks for the feedback and your working PR. But I would prefer the following solution as I think it would be more flexible for the future. Based on your proposal i will integrate this in next version


Remove
 ```
// HTML
@click:append="onEvent($event, obj, append)"
 ```
and replace 
 ```
// HTML 
@[suspendClickAppend(obj)]="onEvent($event, obj, append)"

//methods
suspendClickAppend(obj){
      // select|combobox|autocomplete -> suspend 'click:append' for working down arrow
      return /(select|combobox|autocomplete)/.test(obj.schema.type) ? '' : 'click:append'
},  

```

**Comment by wotamann** [comment]
#69 fixed

**Comment by RyanCwynar** [comment]
Ah, I see what you did there. That's cool. Gets a little more meta with it.
