### ISSUE TITLE
Combox box with object.

### ISSUE THREAD

**Issue by andrelec1** [wotamann/vuetify-form-base#80]
According this: #39 

i want to do something like this : 
```
        'product.asset': {
          flex: 3,
          placeholder: 'Product Asset',
          type: 'combobox',
          items: this.formExtraData.choice.asset,
          returnObject: false,
          itemText: 'code',
          itemValue: 'id',
        },
```

That seem work ... but that not work like intended ...

That use the 'code' property for populating the combobox choice list => ok
That use the 'id' property for populating my model => ok 

But, that update my model and display the id in the combobox :/ 

![image](https://user-images.githubusercontent.com/3273204/100547467-3a88db80-3267-11eb-89a2-342fabdd8769.png)

![image](https://user-images.githubusercontent.com/3273204/100547480-42e11680-3267-11eb-8475-a76995931df1.png)

**Comment by wotamann** [comment]
Thanks for your interest!

This is [Vuetify Issue #5479](https://github.com/vuetifyjs/vuetify/issues/5479), which is discussed here 
[https://vuetifyjs.com/en/components/combobox/](https://vuetifyjs.com/en/components/combobox/)

**Comment by andrelec1** [comment]
So replace 'combobox' by 'autocomplete' because vutify team is wierd as fuck and seem didn't like making consistant lib ....
Thank ...
