### ISSUE TITLE
Storing Value and Schema Objects in a database.

### ISSUE THREAD

**Issue by jackmcbee** [wotamann/vuetify-form-base#9]
Hello wotamann,

you have done a great job with vFormBase. I enjoy using it very much.

I am wondering if it is possible to store the value and schema objects in a database and load them dynamically. 

Somewhat like that.
```
Value: {
}

Schema: {
} 

axios.get('/')
  .then(function (response) {
    this.Value = response.data.Value
    this.Schema = response.data.Schema
 }
```

}

**Comment by wotamann** [comment]
Hello jackmcbee!

You could try to lazy load VFormBase Component

Hope this will help!




      <v-container fluid >

        <v-form v-if="showFormbase">

          <v-form-base :value= "myValue" :schema= "mySchema" @change= "change"/>
        
        </v-form>
      
      </v-container>

 
 ...


      export default {
        components: {  
          // LAZY LOADING 'VFormBase' COMPONENT HERE
          'VFormBase': () => import('@/components/vFormBase'), 
        },
        data () {
          return {
            showFormbase: false, 
            myValue:{},
            mySchema:{}
          }
        },
        
        methods: {
          delay(obj){
            return new Promise( (resolve, reject) => {
              setTimeout(() => { resolve(obj) }, 1000)
            })
          }
        },

        async mounted(){

          // 1) ASYNC LOADING VALUE & SCHEMA 
          this.myValue = await this.delay({
            name: 'Base',
            password: '123456',
            file: [], // contains a single or an array of File objects
            checkbox: true
          })      
          this.mySchema= await this.delay({
            name: { type: 'text', label: 'Name', flex: 4 },
            password: { type: 'password', label: 'Password', clearable: true, flex: 3 },
            file: { type: 'file', label: 'Image-Files', accept: 'image/*', multiple: true, flex: 4 },
            checkbox: { type: 'checkbox', label: 'Ok', flex: 1 }
          })

          // 2) LAZY LOADING 'VFormbase' after making visible 
          this.showFormbase = true
        }
      }

`
